Target link selector test
matsim-org/matsim-libs pull request #1161
Opened 2020-09-17 08:44 UTC by hmarciales

New test for TargetLinkSelector class

2020-09-17 09:48 UTC, tschlenther requested changes

2020-09-17 09:48 UTC, tschlenther commented on contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/DrtZoneTargetLinkSelectorTest.java
> +		assertThat(links.size() == drtZonalSystem.getZones().get("1").getLinks().size());
I think the zone only contains one link, so the result of picking a random link is always the same. I would suggest to rather create a zonal system with one zone only, containing all 4 links (by setting cell size to a value higher than 1000). Then query the random selector a lot of times and test
a) whether all links of that zone have been selected at least once (like you did here)
b) the number of links selected at least once is exactly 4

By explicitly testing b) you make sure that the test class fails when somebody changes the zonal system again.

2020-09-17 10:08 UTC, michalmac approved these changes
Nice. A few comments to consider before merging.

I can help with the first test.

2020-09-17 10:08 UTC, michalmac commented on contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/DrtZoneTargetLinkSelectorTest.java
> +		assertThat(link.getId().toString() ==  "cd");
`assertEquals("cd", link.getId() + "")` should fit better for comparing Strings

2020-09-17 10:08 UTC, michalmac commented on contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/DrtZoneTargetLinkSelectorTest.java
> +	}
Otherwise, there is always some likelihood this test will fail.

2020-09-18 09:08 UTC, hmarciales commented on contribs/drt/src/test/java/org/matsim/contrib/drt/analysis/zonal/DrtZoneTargetLinkSelectorTest.java
> +	}
Thank you Michal, 
yeah your help would be very useful. I do not know very well, what would be a good way to test random stuff

2020-09-28 08:55 UTC, michalmac commented
@hmarciales I created a unit test for `RandomDrtZoneTargetLinkSelector` in #1183. So only `MostCentralDrtZoneTargetLinkSelector` requires unit tests.

A few hints (based on #1183):
- write tests in `MostCentralDrtZoneTargetLinkSelectorTest` (this test structure pattern is widely supported by IDE, so for instance, any renaming of the tested class or moving it to another package will be also automatically applied to the test class)
- instead of creating zonal system for a network, just (manually) create one or two zones with some links in it

2021-01-29 10:10 UTC, tschlenther commented
@michalmac I think this PR got stuck somewhere, sorry. Do we still need it?

2021-02-18 21:30 UTC, michalmac commented
> @michalmac I think this PR got stuck somewhere, sorry. Do we still need it?

I think we can close this one.

2021-02-18 21:30 UTC, closed without merging