add method for detecting delimiter of csv file before reading it enti…
matsim-org/matsim-libs pull request #3123
Opened 2024-02-20 19:47 UTC by simei94

similar to matsim python tools / calibration /analysis.py, a functionality was implemented, which checks the necessary csv files for their delimiter by reading in the first line of the file, before reading the entire file. This especially is useful for scenarios, which have different delimiter settings to the german ";".

2024-02-20 21:02 UTC, steffenaxer commented
Nice, thanks for the contribution. Would it be possible to provide a small unit test with some different separators, e.g. tab semicolon comma. Maybe this could be located in a more prominent package? E.g. CsvOptions?

2024-02-21 15:49 UTC, simei94 commented
I'll add a unit test, you are right, this makes a lot of sense. @rakow what do you think about moving the newly added method to CsvOptions? I think it is a good idea

2024-02-21 16:05 UTC, rakow requested changes
Moving it to a more prominent class would be indeed a good improvement.

2024-02-21 16:05 UTC, rakow commented on contribs/application/src/main/java/org/matsim/application/analysis/population/TripAnalysis.java
> +			delimiterCounts.put(',', firstLine.split(",").length);
I think you could use a util library, something like `StringUtils.countMatches`. The current solution creates unnecessary new strings

2024-02-21 16:05 UTC, rakow commented on contribs/application/src/main/java/org/matsim/application/analysis/population/TripAnalysis.java
> +		Map<Character, Integer> delimiterCounts = new HashMap<>();
I would not create an extra map to store the occurrences. You can just create 3 variables for your delimiters and compare them directly.

2024-02-27 18:12 UTC, simei94 commented on contribs/application/src/main/java/org/matsim/application/analysis/population/TripAnalysis.java
> +		BufferedReader reader = null;
I do not know what you mean by this. Please have a look at my newest commit and tell me if this is solved already

2024-03-05 17:48 UTC, merged