Performance improvements for PrebookingStopActivity
matsim-org/matsim-libs pull request #3307
Opened 2024-06-04 13:27 UTC by marecabo

* Use PriorityQueue for `PrebookingStopActivity.enterTimes`

2024-06-07 14:17 UTC, sebhoerl requested changes

2024-06-07 14:17 UTC, sebhoerl commented on contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/PrebookingStopActivity.java
> +			RequestIdTime rit = leaveTimes.poll();
Actually, you don't even need `rit`, you can just save the `id` as `leaveTimes.poll().id`

2024-06-07 14:17 UTC, sebhoerl commented on contribs/drt/src/main/java/org/matsim/contrib/drt/prebooking/PrebookingStopActivity.java
> +	private record RequestIdTime(Id<Request> id, double time) implements Comparable<RequestIdTime> {
I would call it something like `QueuedRequest`

2024-06-08 07:34 UTC, marecabo commented
@sebhoerl Thanks for the comments, just addressed them.

2024-06-08 08:03 UTC, sebhoerl approved these changes

2024-06-08 08:03 UTC, sebhoerl commented
Great, thanks!

2024-06-08 08:28 UTC, merged